name: CI
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Yarn install and build
        run: yarn install && yarn build
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: and-cru/actions-s3-static-upload@v12
        with:
          milliseconds: 500
          s3-bucket-name: ${{ secrets.S3_BUCKET_STATIC_WEBSITE }}
          folder: build
